modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/MineAndSlashAwaken/issues"

[[mods]]
modId="mineandslashawaken"
version="1.0.0"
displayName="Mine and Slash: Awaken"
description="An addon mod for Mine and Slash."

[[dependencies.mineandslashawaken]]
modId="mine_and_slash"
mandatory=true
versionRange="[6.1.15,)"
ordering="AFTER"
side="BOTH"
